# Generated by Django 5.2 on 2025-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaambiente',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
